#!/bin/bash

current_dir="$(dirname "$0")"

gem install aptible-cli -v 0.5.15

aptible login --email=$APTIBLE_EMAIL --password=$APTIBLE_PASSWORD

# See if project does not exist, and create it
if ! aptible apps | grep -q "^$APTIBLE_APP"; then
  # create project
  aptible apps:create $APTIBLE_APP --account=$APTIBLE_ACCOUNT

  # Set configuration
  aptible config:set FORCE_SSL=true \
    DISABLE_WEAK_CIPHER_SUITES=true \
    DATABASE_URL=$DATABASE_URL \
    S3_BUCKET=$S3_BUCKET \
    S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID \
    S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY \
    MAX_DAYS_TO_KEEP=$MAX_DAYS_TO_KEEP \
    --app=$APTIBLE_APP
fi

# Then push to deploy!
git checkout --orphan "deploy-$CIRCLE_SHA1"
git config user.email "deploy@mdsave.com"
git config user.name "Deploy from CircleCI"
git commit -am "Deployment Commit" -q
git push git@beta.aptible.com:$APTIBLE_ACCOUNT/$APTIBLE_APP.git "deploy-$CIRCLE_SHA1":master --force
